-- PF-2833: the TCSProjectTracker GeoServer workspace publishes its project layers from new TCSI-only
-- views that add the forest fuels reduction treatment acreage columns. Register their primary keys so
-- WFS feature IDs keep using PrimaryKey (see PF-2691 / release script 0573).

INSERT INTO [dbo].[gt_pk_metadata]
           ([table_schema]
           ,[table_name]
           ,[pk_column]
           ,[pk_column_idx]
           ,[pk_policy]
           ,[pk_sequence])
     VALUES
           ('dbo', 'vGeoServerTcsiProjectDetailedLocations', 'PrimaryKey', 1, 'autogenerated', NULL),
           ('dbo', 'vGeoServerTcsiProjectSimpleLocations', 'PrimaryKey', 1, 'autogenerated', NULL)
